// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX4D3e6FjRfcgv95yXrYNYW6FAZv0bcLs',
    appId: '1:489557610879:web:9ac8f210a8a9457971ca4a',
    messagingSenderId: '489557610879',
    projectId: 'mvp241217',
    authDomain: 'mvp241217.firebaseapp.com',
    storageBucket: 'mvp241217.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANbkvGRslOAR4qTNEytbB6P1eQ33QGZQs',
    appId: '1:489557610879:android:592e0d4dcad5237371ca4a',
    messagingSenderId: '489557610879',
    projectId: 'mvp241217',
    storageBucket: 'mvp241217.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxwZitQ63MA9YiD0IZAf0XtxfHdADh9U0',
    appId: '1:489557610879:ios:4687c1240141cfcc71ca4a',
    messagingSenderId: '489557610879',
    projectId: 'mvp241217',
    storageBucket: 'mvp241217.firebasestorage.app',
    iosBundleId: 'com.example.mvp241217',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxwZitQ63MA9YiD0IZAf0XtxfHdADh9U0',
    appId: '1:489557610879:ios:4687c1240141cfcc71ca4a',
    messagingSenderId: '489557610879',
    projectId: 'mvp241217',
    storageBucket: 'mvp241217.firebasestorage.app',
    iosBundleId: 'com.example.mvp241217',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX4D3e6FjRfcgv95yXrYNYW6FAZv0bcLs',
    appId: '1:489557610879:web:43ecfc17e2b0c33b71ca4a',
    messagingSenderId: '489557610879',
    projectId: 'mvp241217',
    authDomain: 'mvp241217.firebaseapp.com',
    storageBucket: 'mvp241217.firebasestorage.app',
  );

}